spring:
    application:
        name: api
    datasource:
    # The TNS alias name from your tnsnames.ora (like "adb_high" or "adb_tp")
      url: jdbc:oracle:thin:@adplearn_high?TNS_ADMIN=D:\\Main_everything\\AIProjects\\Adaptive_learning\\support_notes\\Wallet_adplearn
      username: ADMIN
      password: Oracleadm@11    
      driver-class-name: oracle.jdbc.OracleDriver

    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.OracleDialect

openai:
  api:
    key: ${OPENAI_API_KEY}
